Update Home.tsx
StratosphereLabs/flight-logger pull request #80
Opened 2023-02-18 18:57 UTC by TechnicallyGio

Uses Modal to create flights rather than changing the view focus. Modal needs to be wider.

2023-02-18 19:37 UTC, SuperCheese21 commented on resources/pages/Home/Home.tsx
> +      <Modal
You can use the `className` prop on the `Modal` component to set the width manuallu

2023-02-18 19:43 UTC, SuperCheese21 commented on resources/pages/Home/Home.tsx
> +import {Form, Modal} from 'stratosphere-ui';
Looks like you don't have format on save enabled. Could you please run `npm run format` and commit the changes?

2023-02-18 19:43 UTC, SuperCheese21 commented on resources/pages/Home/Home.tsx
> +      {/*
Please remove this code if it is not needed anymore

2023-02-18 21:37 UTC, TechnicallyGio commented on resources/pages/Home/Home.tsx
> +      <Modal
Did not work

2023-02-18 21:37 UTC, TechnicallyGio commented on resources/pages/Home/Home.tsx
> +import {Form, Modal} from 'stratosphere-ui';
will do

2023-02-18 21:40 UTC, TechnicallyGio commented on resources/pages/Home/Home.tsx
> +      {/*
Resolved

2023-02-19 00:29 UTC, SuperCheese21 commented
Form is not responsive. Please make sure modal width adjusts in mobile mode.

2023-02-19 00:54 UTC, SuperCheese21 requested changes
- [x] Form is not responsive. Please make sure modal width adjusts in mobile mode.

2023-02-20 04:44 UTC, SuperCheese21 approved these changes

2023-02-20 04:44 UTC, merged